### ISSUE TITLE
Should FLOAT_CMP be used by default all cases of floating point comparison?

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-doctestplus#10]
See https://github.com/astropy/astropy/issues/6312 for discussion. I think the idea here would be that the `+FLOAT_CMP` annotation would not be required, but instead all tests involving equality between floating point numbers would automatically use approximate comparisons.

**Comment by astrofrog** [comment]
Maybe this could be a globally configurable option (i.e. the plugin should still provide a way to do it on a case by case basis, but we could have an option to enable it by default?)

**Comment by bsipocz** [comment]
I like @astrofrog's idea. Originally though about making the opposite, NO_FLOAT_CMP annotation, but his idea is much better sounding.

**Comment by StanczakDominik** [comment]
YES! This definitely needs to be a thing. It would be awesome to have this!
