### ISSUE TITLE
Why is this not part of pytest?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-doctestplus#100]
We have compatibility problems once in a while, making me think, since none of these features are astronomy specific, why this is code not part of pytest?

**Comment by bsipocz** [comment]
I don't see this any different than the other plugins, and pytest's approach is to work with plugins. 🤷‍♀

**Comment by pllim** [comment]
But the code here inherits a lot from `_pytest/doctest.py`.

**Comment by Cadair** [comment]
As there is already some doctest support in pytest it feels like it would not be out of scope if this were to be moved in. Why don't we ask the pytest devs if they would have it. If this needs a major refactor for 5.4 it sounds like the perfect opportunity to refactor it into core.

**Comment by bsipocz** [comment]
Then we must have this separately due to "historical reasons". A lot has changes since, so if they would take this into core, it would be great of course!

**Comment by bsipocz** [comment]
What do you think @nicoddemus, ☝️

**Comment by nicoddemus** [comment]
Hi everyone 👋,

Full disclosre, I'm not a user of doctests in general (although I've contributed to pytest's doctest support in the past).

I see the following `pytest-doctestplus` features that are not available in pytest's core:

* Float comparison
* Ignoring warnings
* Skip unconditionally
* Dependencies
* Remote Data (depends on `pytest-remotedata`)

All of them (except perhaps for "Remote Data" support) seem reasonable to have in the core.

As @bsipocz mentions, usually we prefer to extend pytest through plugins, but for features of the standard library where there's really not much diverting ways to go about it, integrating that feature into the core makes sense. To me doctesting falls into that category.

For an example of a feature that's in the standard library but we don't have plans to integrate into the core is `async` support: `asyncio` is in the standard library, but there are other libraries with asynchronous support , like `trio` and `twisted`, so it makes sense to have separate plugins for each: `pytest-asyncio`, `pytest-trio`, and `pytest-twisted`. 

Integrating this to the core would require a champion however, someone who's willing to do the integration work and step up on occasion to help fix bugs on that module if they appear (of course core devs often help here, but is nice to have a champion/expert to turn to).

One advantage is that there would be no more compatibility problems, as they are now in the core so compatibility is guaranteed.

Having said all that, if a champion steps up, I would definitely be 👍 to integrate `pytest-doctestplus` into the core. I'm sure it would be very much appreciated by doctest users, as it introduces some very nice features.

@RonnyPfannschmidt @bluetech, opinions?

**Comment by RonnyPfannschmidt** [comment]
personally i would prefer to merge the internal doctest plugin and this one into a pytest plugin thats outside of core but installed by default

personally i also dont use/avoid doctests

**Comment by nicoddemus** [comment]
> personally i would prefer to merge the internal doctest plugin and this one into a pytest plugin thats outside of core but installed by default

Perhaps, as this brings logistics problems about how to test it properly with pytest to solve the compatibility problem brought up here, but either way the first step would be to merge it into the core, and then discuss it how to split it as a separate plugin. 👍

**Comment by pllim** [comment]
Re: champion -- pinging @astropy/coordinators

**Comment by pllim** [comment]
Re: remote-data -- Yeah, maybe that can stay here or go to `pytest-remotedata` somehow.

**Comment by bsipocz** [comment]
Naively I don't think that can really go to remote data though as that's the bare minimum the doctests to know about the concept of remote-data

**Comment by pllim** [comment]
Also see https://github.com/pytest-dev/pytest/discussions/8088

**Comment by pllim** [comment]
Alas, this never happened, so now superseded by #199.
