### ISSUE TITLE
TST: Test against pytest dev

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-doctestplus#102]
As @bsipocz suggested, perhaps this packages needs to be tested against pytest dev (maybe as allowed failure). However, I am not sure how to implement it. Theoretically, it would be implemented over at `ci-helpers` but currently we have

https://github.com/astropy/ci-helpers/blob/661e07eb91dad30a3f0ccebd16e10c3c468c494e/travis/setup_dependencies_common.sh#L266-L270

**Blocked by** #95

**Comment by bsipocz** [comment]
good point about the pinning, I'll cook up something that works on the ci-helpers level, and not an utterly disgusting hack.

**Comment by pllim** [comment]
Looks like we do it already?
