### ISSUE TITLE
sphinx doctest

### ISSUE THREAD

**Issue by awaelchli** [astropy/pytest-doctestplus#104]
Hi

Is there a way to make doctestplus aware of the directives of sphinx doctest, e.g., the ".. testsetup::"?
https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html

**Comment by bsipocz** [comment]
We do successfully use `testsetup` along with doctestplus, so I'm not there is any actionable task here.

(e.g. https://raw.githubusercontent.com/astropy/astropy/master/docs/coordinates/galactocentric.rst)

**Comment by awaelchli** [comment]
Thanks! My bad, I forgot the >>> in my test setup, that's why it didn't work.
Awesome! Now I can use doctestplus!
