### ISSUE TITLE
Q: should I use sphinx doctest or doctestplus to test docs?

### ISSUE THREAD

**Issue by awaelchli** [astropy/pytest-doctestplus#105]
Can/should doctestplus be used together with sphinx or not?

I noticed some differences. For example, the [skipif](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#skipping-tests-conditionally) directive and other seem to be incompatible with doctestplus. 

Works with sphinx `make doctest`, but is ignored by doctestplus:
```
.. doctest::
    :skipif: torch.cuda.device_count() < 2
```

Works with sphinx but is ignored with doctestplus:
```
.. testsetup:: *
    import numpy
```
However, to make it work in doctestplus, we have to add >>>:
```
.. testsetup:: *
    >>> import numpy
```
But then it gives a syntax error with sphinx `make doctest`.

If sphinx can run doctests (in rst), then what is this library for?

**Comment by bsipocz** [comment]
> If sphinx can run doctests (in rst), then what is this library for?

I'm not sure what to do with a loaded question like this. 

`pytest-doctestplus`, as the readme says, a pytest plugin. It has nothing to do with sphinx, beyond that sphinx is rendering the same `rst` files for documentation purposes. Pytest collects code snippets from the documentation, so you don't run `make doctest` but `pytest`. And yes, it has some peculiarities, e.g. `>>>` is needed to flag code to be collected for testing.

**Comment by awaelchli** [comment]
> I'm not sure what to do with a loaded question like this.
I certainly did not mean to be impolite. I should have formulated it differently. All I'm trying to figure out is how to do doctests and currently I have found two ways: one is with sphinx and the other is pytest + doctestplus. To me it seems that they are incompatible but I was not sure so I asked.

**Comment by awaelchli** [comment]
Thanks for the quick answer.
