### ISSUE TITLE
add `doctest_ignore_import_errors_modules`

### ISSUE THREAD

**Issue by bsipocz** [astropy/pytest-doctestplus#110]
Instead of a blank bool `doctest_ignore_import_errors` option, add that takes a string value for list of files/modules where imports should be ignored. E.g. that should be used to skip import issues for e.g. `setup_package.py` files, etc.
With this the plugins behaviour could match the pytest native doctest more, while we can keep some of the flexibility we needed for `extension_helpers`/`astropy_helpers`.

**Comment by pllim** [comment]
@astrofrog pointed out that this can be similar to https://github.com/astropy/astropy/blob/a0f5940bd00ff7259ed6b2391bfddecd007a2a43/setup.cfg#L95

**Comment by astrofrog** [comment]
I think I have a clean solution, I'll open a PR shortly

**Comment by astrofrog** [comment]
See #112
