### ISSUE TITLE
[0.7] ImportMismatchError with package test

### ISSUE THREAD

**Issue by olebole** [astropy/pytest-doctestplus#114]
When testing the package itself, I run into the following error:
```
____________ ERROR collecting pytest_doctestplus/output_checker.py _____________
323 /usr/lib/python3/dist-packages/pytest_doctestplus/plugin.py:175: in collect
324     module = self.fspath.pyimport()
325 /usr/lib/python3/dist-packages/py/_path/local.py:721: in pyimport
326     raise self.ImportMismatchError(modname, modfile, self)
327 E   py._path.local.LocalPath.ImportMismatchError: ('pytest_doctestplus.output_checker', '/usr/lib/python3/dist-packages/pytest_doctestplus/output_checker.py', local('/tmp/autopkgtest-lxc.8sgijvfm/downtmp/build.NlB/src/pytest_doctestplus/output_checker.py'))
```
The same happens for `pytest_doctestplus/plugin.py` and `pytest_doctestplus/utils.py`.
Full test log [here](https://salsa.debian.org/python-team/modules/pytest-doctestplus/-/jobs/755915).

**Comment by bsipocz** [comment]
I'm afraid we never pinpointed this down to something, do you still see this error?

**Comment by olebole** [comment]
This was finally resolved by running the test from a directory outside of the source package.

**Comment by nstarman** [comment]
Would changing to a src layout help?

**Comment by olebole** [comment]
Probably yes, but changing directory is not a big deal here, and is not worth the effort. Directly running the test for the installed package from the source dir was just wrong; this is corrected now.
