### ISSUE TITLE
Conda package for pytest-doctestplus does not respect minimum Python version

### ISSUE THREAD

**Issue by hamogu** [astropy/pytest-doctestplus#115]
Sherpa uses doctestplus (through astropy) and we've seen our CI fail, once pytest-doctestplus dropped support for Python 3.5 (which we still have). It seems that this is due to the fact that the conda packages don't know about the minimum Python requirements:
https://github.com/sherpa/sherpa/pull/826

P.S.: I know that this is not the right repro to report conda packaging issues, but I don't know who builds the conda packages and where, so I'm hoping that that person reads this and can move the issue.

**Comment by bsipocz** [comment]
Oh, right. Indeed the conda package don't have any python version limitation added, but I don't have access to move the issue to the feedstock. https://github.com/conda-forge/pytest-doctestplus-feedstock

Here are the people you can ping about it, maybe it's also a good time to update the names:

```
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
```

**Comment by bsipocz** [comment]
(Normally though I would suggest to NOT use conda for testing infrastructure dependencies. PyPI releases are more frequent, but they are not necessarily followed by conda-forge updates)

**Comment by hamogu** [comment]
I just learned that @Marie-Terrell is more clever than I am and actually found the correct repository:
https://github.com/astropy/conda-channel-astropy/issues/181
