### ISSUE TITLE
TypeError: _importconftest() missing 1 required positional argument: 'importmode'

### ISSUE THREAD

**Issue by jdavies-st** [astropy/pytest-doctestplus#116]
The following error is seen when using `pytest-doctestplus` with `pytest` dev versions after 5.4 and with the latest `pytest 6.0rc1` pre-release.

https://travis-ci.org/github/astropy/pytest-doctestplus/jobs/704222114#L699-L714

**Comment by pllim** [comment]
Fixed in #120
