### ISSUE TITLE
How to use pytest-doctestplus in my project.

### ISSUE THREAD

**Issue by yashwant121** [astropy/pytest-doctestplus#117]
Can someone please tell me how to add pytest-doctestplus to my project. 
Why Can't I import it like a module 

**import pytest-doctestplus.**

And if not this way then how can i use it as a plugin.
Please help me out as I am complete beginner.

[normally to get doctest I just have to write]

**import doctest.**

**Comment by pllim** [comment]
This is a pytest plugin. Please refer to pytest documentation about usage of plugins.
