### ISSUE TITLE
Need a new release to be compatible with pytest 6.0.0

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-doctestplus#121]
The fix in #120 needs to be released.

**Comment by pllim** [comment]
From the info at https://pypi.org/project/pytest-doctestplus/, looks like either @astrofrog or @bsipocz can do this. You also probably want to remove Dan from PyPI side.

**Comment by mhvk** [comment]
Definitely hitting my packages too.  Sounds like we need a `pytest-dev` CI run, perhaps in astropy as part of the numpy-dev one?

**Comment by pllim** [comment]
There is:

https://github.com/astropy/pytest-doctestplus/blob/44cc6d1e42e6c8961632f5e69d2edf99685f6ace/.travis.yml#L42

There is even a weekly cron job, but I guess no one is checking:

https://travis-ci.org/github/astropy/pytest-doctestplus/builds/711006188

**Comment by mhvk** [comment]
Ouch. Maybe having it used on astropy would be better in that regard. It does make one wonder about splitting pieces off...

**Comment by pllim** [comment]
Astropy Project just hired a "operational specialist," so hopefully all the pieces will be better maintained going forward. I don't think the core should pickup extra jobs just because pieces like this fall behind in maintenance.

**Comment by mhvk** [comment]
Yes, makes sense. On the other hand, not so strange to test astropy against development versions of *all* its critical dependencies. But even better to have someone think through properly how best to organize.

**Comment by bsipocz** [comment]
To be frank this would not have fallen behind if the constant mantra from certain loud people are not the "infrastructure is not important", "we don't want to talk about infrastructure", etc. Let alone the constant gatekeeping on GitHub access (what would be needed for experimenting with more ci/cd integrations etc). E.g the last two of those took 1-2 years to finally opt in, reluctantly, after the community decision was made. And that kills the souls of those who would drive the changes.

 But that's just the tip of the iceberg.

Solving it with money is a solution, but not at all a sustainable one, as that approach was tried in the past and apparently failed.

**Comment by bsipocz** [comment]
>  But even better to have someone think through properly how best to organize.

And make sure that someone is not ignored, which would be the status quo. See the lack of any of these generic, every day and DevOps roles listed on the team page, see the constant complains about "barriers are high, I just want my hack in, preferably at the last possible minute (astronomers and deadlines)", or even just the recent complaints against being careful about e.g warnings in CI.

**Comment by mhvk** [comment]
@bsipocz - let's be sure to put this as the first agenda item for the next astropy meeting. My aversion to meetings of any kind means I have little clue what exactly was decided, what was not done, etc., but I do know that ensuring that contributions are both enabled and recognized is important for all of us. Indeed, I don't even know if I've been one of the people blocking progress (if so, definitely not intended).

**Comment by mhvk** [comment]
p.s. I've written to the coordinators asking for infrastructure to be on the agenda -- as well as putting in place better procedures for dealing with feature freeze the next time.

**Comment by saimn** [comment]
I guess something could be done to have all least better notifications for failing cron builds. Maybe sending them to a slack channel so that more people can see them ? It is possible to filter notifications to send only the cron ones, and maybe failure on master: https://docs.travis-ci.com/user/notifications/#conditional-notifications

**Comment by pllim** [comment]
By the power vested in me, I'll do a PyPI release. We can move the maintenance improvement discussions to a new issue. Thanks!

**Comment by pllim** [comment]
0.8.0 is on PyPI now. Hopefully `conda-forge` will pick it up in a week.

**Comment by mhvk** [comment]
Hear, hear!! Thanks so much, @pllim!
