### ISSUE TITLE
doctest-skip-all is not documented

### ISSUE THREAD

**Issue by Cadair** [astropy/pytest-doctestplus#126]
or I am looking with my eyes closed.

**Comment by pllim** [comment]
Apparently not where people look... https://github.com/astropy/pytest-doctestplus/search?q=doctest-skip-all

**Comment by Cadair** [comment]
This thing supports tex files?!

**Comment by pllim** [comment]
Surprise!

**Comment by bsipocz** [comment]
Of course it supports, how else could I CI test all the code examples in the astroML book? 😜

**Comment by Cadair** [comment]
excellent.
