### ISSUE TITLE
Is it possible to add an option to run only doctests?

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-doctestplus#14]
The idea would be that running `pytest --doctest-only` would run all doctests, but no other tests. This would have to hook the default collection mechanism in `pytest`, which may be complicated.

cc @Cadair

**Comment by rs2** [comment]
👍

**Comment by radkujawa** [comment]
:+1:

**Comment by vanyakosmos** [comment]
Tests and package code are separated anyway, I think that there is no need for such flag.

- `pytest docs` - for docs
- `pytest src` - for code and its doctests
- `pytest tests` - for tests

**Comment by vanyakosmos** [comment]
Okay, astropy seems to be exception to these rules. And this flag can be useful for #77.
But better solution is to make `--ignore` and` --ignore-glob` work (#58).

**Comment by Cadair** [comment]
Doctests can also be in docstrings of functions, so filtering by top level folder even if you are not astropy isn't always viable. `--ignore-glob=test_*.py` would probably cover most of this use though.

**Comment by bsipocz** [comment]
this should be really done at the collection level, rather than with ignore magic. imo
