### ISSUE TITLE
Raise error when remote data is accessed without using the remote-data directive

### ISSUE THREAD

**Issue by tinumide** [astropy/pytest-doctestplus#145]
Currently there is no error if remote data is accessed without using the directive for remote data (unlike for the remote-data decorator when an IOError is raised with "An attempt was made to connect to the internet". 

_Originally posted by @bsipocz in https://github.com/astropy/pytest-doctestplus/issues/137#issuecomment-749886094_

**Comment by bsipocz** [comment]
This has been fixed for a while, so I'm closing the issue.
