### ISSUE TITLE
add directive to enable something like "skip if"

### ISSUE THREAD

**Issue by eteq** [astropy/pytest-doctestplus#16]
A constant thorn in our side when writing doc tests for `astropy.coordinates` is the need to ``# doctest: +SKIP`` anything that uses scipy, since it's an *optional* dependency.  It would be better if we could do something like ``# doctest: +SKIP_IF_HAS_SCIPY``.  doctestplus might be a good place for this, but the challenge is: how to define this sensibly?  ideally one would have a skipif that's fairly generic, not hard-coded to Scipy...

cc @drdavella

**Comment by bsipocz** [comment]
@eteq - wouldn't the `.. doctest-requires: scipy` directive be a good alternative for now? Afaik you still have to state it before each snippet, but it's still way better than adding `SKIP` to every line.

**Comment by drdavella** [comment]
I wonder if another directive that evaluates arbitrary conditions would be useful. Something like:
`.. doctest-skipif:

**Comment by oscarbenjamin** [comment]
Sympy's test runner has solved this using a decorator to mark a particular function/class for skipping. 

You can see the decorator here: [https://github.com/sympy/sympy/blob/sympy-1.3/sympy/utilities/decorator.py#L130](https://github.com/sympy/sympy/blob/sympy-1.3/sympy/utilities/decorator.py#L130)

Also an example of use is here: [https://github.com/sympy/sympy/blob/sympy-1.3/sympy/printing/preview.py#L23](https://github.com/sympy/sympy/blob/sympy-1.3/sympy/printing/preview.py#L23)

I'm not sure if doctestplus should grow something as complicated as that but certainly a decorator for skipping doctests would be useful. As long as doctestplus has the machinery to skip doctests from a marked function then downstream projects can extend that with as much conditional functionality as they like.

So I would suggest just to keep it simple and add a decorator called `doctest_skip`.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/sphinx-doc/sphinx/pull/5307/ is also a potential implementation and closer to the restructuretext bits

**Comment by bsipocz** [comment]
as per my comment above I think we have this functionality already. At least for that was my understanding reading the narrative of the OP. Reading the example is something else though, so if you indeed mean adding functionality that SKIPs when something is installed, then please reopen and provide more details about the use case you have in mind.
