### ISSUE TITLE
BUG: doctest-remote-data block directive hides code in Sphinx

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-doctestplus#161]
https://github.com/astropy/astroquery/issues/2111#issuecomment-879497426 

I think the problem is there is no Sphinx directive defined for the new `.. doctest-remote-data::` directive in https://github.com/astropy/pytest-doctestplus/blob/main/pytest_doctestplus/sphinx/doctestplus.py . Hopefully the implementation of `.. doctest-skip::` would be a good example to follow.

So, in a way, #137 was incomplete. Perhaps instead of testing that PR in `astropy` before merge, we should have also tested it in `astroquery`.

If a fix cannot be done soon, we might need to revert #137 and do another bug fix release, and then re-apply it in the future together with the new sphinx directive. 🤔

**Comment by bsipocz** [comment]
Fix is done in sphinx-astropy.
