### ISSUE TITLE
Add directive supporting the use of remote data in doctests

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-doctestplus#2]
Something like `.. remote-data`, perhaps.

EDIT: `astroquery` relies on this feature to exist before they can enable doctest.

**Comment by kakirastern** [comment]
Hi, is it okay for me to work on this issue?

**Comment by kakirastern** [comment]
Thanks @bsipocz for the approval! Will follow up on this soon after investigating on the issue further.

**Comment by bsipocz** [comment]
you don't need to ask for permission to work on issues. If there are work in progress it is most probably cross linked somewhere in the issues.

**Comment by kakirastern** [comment]
Yup @bsipocz, understood.

**Comment by kakirastern** [comment]
I am guessing (albeit an educated one) that I will need to modify at least the file at "pytest-doctestplus/pytest_doctestplus/output_checker.py", plus some other tests too...

**Comment by kakirastern** [comment]
So something in the line of https://github.com/astropy/astropy/issues/2830#issuecomment-51439529 are to be implemented... 

``` 
class DoctestRemoteDirective(Directive):
    ... do something with the pytest config.getoption('remote_data') ...

def setup(app):
    app.add_directive('doctest-remote', DoctestRemoteDirective)
    app.add_directive('doctest-remote-all', DoctestRemoteDirective)
```
- [ ] Write a sphinx extension (Reference: [http://www.sphinx-doc.org/en/stable/extdev/tutorial.html](http://www.sphinx-doc.org/en/stable/extdev/tutorial.html))
- [ ] Get `config` into the `DoctestXDirective`'s namespace, where `config` refers to an object found in "pytest_plugins.py", or some file to the same effect

**Comment by kakirastern** [comment]
To self: Some other reference which may be useful regarding the `OutputChecker` and `DocTestRunner` classes relevant to the `doctest.register_optionflag` flag option in the proposed PR: [https://docs.python.org/3/library/doctest.html#doctest.register_optionflag](https://docs.python.org/3/library/doctest.html#doctest.register_optionflag)
