### ISSUE TITLE
--doctestplus ignores collect_ignore

### ISSUE THREAD

**Issue by oscarbenjamin** [astropy/pytest-doctestplus#33]
I've been testing using doctestplus with SymPy and have run into an issue to do with blacklisting files for collection.

SymPy's `conftest.py` blacklists the `sympy/integrals/rubi/rubi_tests` directory with
```python
# Collecting tests from rubi_tests under pytest leads to errors even if the
# tests will be skipped.
collect_ignore = ["sympy/integrals/rubi/rubi_tests"]
```

Running with `pytest` or `pytest --doctest-modules` does not attempt to collect tests from any file under that directory. This is needed because importing some of these files leads to errors.

Running with `--doctest-plus` imports all of the files under that directory ignoring the `collect_ignore` blacklist. Is that a bug in pydoctestplus or should sympy use a different mechanism to blacklist these files?

Related: running with `--doctest-plus` also leads to errors from the files under the `sympy/parsing/autolev/test-examples` directory. These files are ignored when running without `--doctest-plus`. Presumably that's because `test-examples` is not a valid package name. Should files from there be collected by doctestplus?

**Comment by drdavella** [comment]
It seems like you might want to add these directories to `norecursedirs` in the `[tool:pytest]` section of your `setup.cfg`. It's possible that this plugin should also respect `collect_ignore`, but hopefully this workaround will suffice for now.

**Comment by oscarbenjamin** [comment]
Thanks. I've got it started using `norecursedirs` now.

The README for this plugin says 
```
The plugin is applied to all directories and files that pytest collects. This means that configuring testpaths and norecursedirs in setup.cfg also affects the files that will be discovered by pytest-doctestplus. In addition, this plugin provides a doctest_norecursedirs configuration variable that indicates directories that should be ignored by pytest-doctestplus but do not need to be ignored by other pytest features.
```
To me that suggests that it will respect the same collection options as pytest (and the default doctest plugin).
