### ISSUE TITLE
doctestplus ignores doctest_optionflags options in pytest.ini

### ISSUE THREAD

**Issue by oscarbenjamin** [astropy/pytest-doctestplus#38]
I've almost got doctestplus and sympy to play nicely together but I have a few outstanding issues.

One is that I need a way to set the `IGNORE_EXCEPTION_DETAIL` doctest option. This is set in `pytest.ini` like
```ini
doctest_optionflags =
    NORMALIZE_WHITESPACE
    IGNORE_EXCEPTION_DETAIL
    ELLIPSIS
```

However doctestplus ignores these flags and always uses `NORMALIZEWHITESPACE` and `ELLIPSIS` but not `IGNORE_EXCEPTION_DETAIL`.

Would it not be better to get these flags from the pytest config?

I also want a way to set `FLOAT_CMP` globally - maybe it could go in `pytest.ini` with the other flags as well...

**Comment by drdavella** [comment]
There is an issue open for setting `FLOAT_CMP` globally: #10. It does seem like a good idea.

It would be good to honor `doctest_optionflags`.
