### ISSUE TITLE
Doctests stop at first failure

### ISSUE THREAD

**Issue by bsipocz** [astropy/pytest-doctestplus#44]
When I run the doctests with `pytest -m doctest -v filename` then all the code snippets are run even when there are failing ones. However with `pytest --doctest-plus path` the test only run until the first failure. 
My question whether we could change the default behaviour here to be the former?

**Comment by vanyakosmos** [comment]
In my case `pytest -m doctest -v foo.py` didn't even find any doctests in file.
Whereas  `pytest --doctest-plus foo.py` found everything and run all tests without stopping on failed.

<img width="887" alt="Screen Shot 2019-11-02 at 19 59 10" src="https://user-images.githubusercontent.com/16745500/68075025-4592e300-fdab-11e9-9e1b-abfd95e82e22.png">

**Comment by vanyakosmos** [comment]
Okay, you probably meant testing of text files (such as `.rst`). I can confirm that whole file is treated as one huge test function. I'm sure if this is necessarily a bad thing. Such behaviour allow to setup variables in one doctest and then use them in another. But at the same time it may also introduce some unexpected behaviour, magic with previously defined state and inability to verify that doctests after failed one work as expected.

Also I still wasn't able to run `pytest -m doctest` properly. With specified `.rst` file and nothing else it just returns `collected 1 item / 1 deselected`.

But `pytest --doctest-glob='*.rst' file` did the trick. Aaaaaand... It behaves exactly like doctestplus: 1 file with multiple doctests - 1 huge test.

Is this really a bug?

**Comment by bsipocz** [comment]
I need to dig up the example, but it definitely was a bug, as the behaviour was better without doctestplus.

**Comment by vanyakosmos** [comment]
For python files we search for available files in module, and then split each file into set of examples:

https://github.com/astropy/pytest-doctestplus/blob/9c92e9c629b234ea9a186561dcd576d5c5c066dd/pytest_doctestplus/plugin.py#L135-L143

But text files are just thrown into `doctest.testfile` without splitting into examples:

https://github.com/astropy/pytest-doctestplus/blob/9c92e9c629b234ea9a186561dcd576d5c5c066dd/pytest_doctestplus/plugin.py#L160-L164

And also wrapper class for python files inherits `doctest_plugin.DoctestModule` but wrapper for text files inherits `doctest_plugin.DoctestItem, pytest.Module`. I'm not sure what is the difference but it's probably also part of the problem.
