### ISSUE TITLE
Make numpy an optional dependency

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-doctestplus#5]
It seems like `numpy` shouldn't be required just to use this plugin. However, if `numpy` is available,  then the `FLOAT_CMP` checks should work as expected.

**Comment by vanyakosmos** [comment]
Yeah, `numpy` is huge package and using it for just one call of fizz-bazz-level function is definitely overkill.

**Comment by bsipocz** [comment]
done by #69
