### ISSUE TITLE
Feature Request: slow option

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-doctestplus#51]
As brought up in astropy/astropy#8461, to run resource intensive (slow) test that does not require remote data, there is a need for a new directive like `SKIP: SLOW` or something similar to skip "slow" tests.

**Comment by SG004** [comment]
Any starting points or recommendations for how I should go about this?

**Comment by pllim** [comment]
I am actually not sure. To implement its own `--slow` marker might conflict with other plugins like `ci-watson`, since that is a common example. I didn't spend much time thinking about this. 😬
