### ISSUE TITLE
Respect `ignore`

### ISSUE THREAD

**Issue by jayvdb** [astropy/pytest-doctestplus#58]
https://github.com/coala/coala-bears setup.cfg includes `--ignore=tests/python/bandit_test_files/` , as they are unparsable python code.  When I try to use doctestplus, these files are found and imported, resulting in an error.

**Comment by jayvdb** [comment]
The default doctest plugin also provides `doctest-ignore-import-error`, which may be the feature that doctestplus needs to add.

**Comment by jdavies-st** [comment]
Another way to do this is
``` ini
[tool:pytest]
norecursedirs = tests/python/bandit_test_files
```
And then `pytest` won't even collect them.

**Comment by jdavies-st** [comment]
Apparently there's also
``` ini
[tool:pytest]
doctest_norecursedirs = tests/python/bandit_test_files
```
Though it might best to prevent collection at the `pytest` level rather than the plugin level.
