### ISSUE TITLE
How to specify text_file_format in config?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-doctestplus#59]
I want to get rid of `UserWarning` seen in astropy/astropy#7928 and I think I can do it as long as I can figure out where to put this `text_file_format = 'rst'` option. Is it in `setup.cfg` or `conf.py`? Which section? Do I need quotes (`'rst'` vs `rst`) in the setting?

https://github.com/astropy/pytest-doctestplus/blob/720266fcc37e878c25f8b832ff10677dabacaad7/pytest_doctestplus/plugin.py#L206-L214

**Comment by bsipocz** [comment]
At the place I use `text_file_format`, I added it to `pytest.ini`, so my best guess is that it should work if you  add `text_file_format = rst` to the pytest section in `setup.cfg`

**Comment by bsipocz** [comment]
fyi that pytest.ini looks like this:
```
[pytest]
addopts = --doctest-plus
text_file_format = tex
doctest_rst = True
testpaths = Chapter1 Chapter10 Chapter11 Chapter2 Chapter3 Chapter4 Chapter5 Chapter6 Chapter7 Chapter8 Chapter9 Appendix
doctest_optionflags =
    NORMALIZE_WHITESPACE
    ELLIPSIS
    FLOAT_CMP
```

So no quotes are needed.

**Comment by bsipocz** [comment]
(but then when it's not provided it should fall back to `rst`, so it's really is instead a bug here.

https://github.com/astropy/pytest-doctestplus/blob/1fe34e0a3ea6c294c71127efa8718ccb56c2e97d/pytest_doctestplus/plugin.py#L290-L297

**Comment by bsipocz** [comment]
never mind, now I remember, the warning is intentional.

**Comment by pllim** [comment]
Thanks! I'll report back when I get a chance to try out https://github.com/astropy/pytest-doctestplus/issues/59#issuecomment-508295599

**Comment by bsipocz** [comment]
@pllim - I've added it to astropy core in https://github.com/astropy/astropy/pull/8955

**Comment by pllim** [comment]
Ah, okay. I'll close this then. Thanks!
