### ISSUE TITLE
Is it time for a release?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-doctestplus#64]
At the time of this writing, the last release was 2019-03-06, more than 5 months ago. There have been patches to `master` since then.

**Comment by bsipocz** [comment]
Are there failures downstream that require a release? (I suppose then we can tag one, otherwise it may make sense to keep the releases close to the astropy ones)

**Comment by bsipocz** [comment]
ah, ok, indeed, that was a pytest 5.1 issue. 

Will tag on release then sooner rather than later, thanks for the ping.

**Comment by astrofrog** [comment]
According to the changelog there are no changes since the last release though :wink:

**Comment by wtbarnes** [comment]
FWIW, I'm also seeing the error that was fixed in #63 (see [here](https://gitlab.com/wtbarnes/aiapy/-/jobs/286858148), it pops up locally as well). A release with this fix would be much appreciated!

**Comment by juliotux** [comment]
+1 with the need of a new release. I'm also having the #63 error in my CI.

**Comment by bsipocz** [comment]
Release is tagged and will land on pypi tomorrow.

**Comment by pllim** [comment]
Thank you!
