### ISSUE TITLE
Use --doctest-glob instead of custom collector for RST files

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-doctestplus#9]
It seems like it should be possible to replace the custom doctest collector used for RST files with the `--doctest-glob` option provided by `pytest`:
https://docs.pytest.org/en/latest/doctest.html#doctest-integration-for-modules-and-test-files

**Comment by vanyakosmos** [comment]
Does this mean that we need to delete `--doctest-rst` option? This will break backward compatibility.
