### ISSUE TITLE
No module named 'pkg_resources' on our CI

### ISSUE THREAD

**Issue by nabobalis** [astropy/pytest-doctestplus#93]
We are running an online build on Python 3.8 and we got this:

```
File "/home/vsts/work/1/s/.tox/py38-online/lib/python3.8/site-packages/pytest_doctestplus/utils.py", line 20, in init
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

I thought that `pkg_resources` was in from Python 3.7, so I am unsure what to make of this or how to proceed.

**Comment by bsipocz** [comment]
it's rather from setuptools. Could it be that you somehow don't have that installed?

**Comment by nabobalis** [comment]
If that's the case, I've been a large idiot.

**Comment by bsipocz** [comment]
Well, setuptools is not explicitly listed for pytest-doctestplus, so if you run into this, this is a rather valid issue.

**Comment by bsipocz** [comment]
@astrofrog - Could you please transfer this issue to https://github.com/astropy/pytest-doctestplus/? I don't have the power.

**Comment by bsipocz** [comment]
@nabobalis - if this is for a public project, could you link to the CI build?

**Comment by nabobalis** [comment]
Sure:

https://dev.azure.com/sunpy/sunpy/_build/results?buildId=5654&view=logs&jobId=a7b3aa55-7d57-562f-3433-7f6b2d4252da&j=a7b3aa55-7d57-562f-3433-7f6b2d4252da&t=b2ae32db-b3b2-5365-a454-2e23b5ad5df8

or 

https://app.circleci.com/jobs/github/sunpy/sunpy/38485/parallel-runs/0/steps/0-108

**Comment by astrofrog** [comment]
@bsipocz - this already appears to be in the correct issue tracker

**Comment by bsipocz** [comment]
🤦‍♀ - apparently I can't read, somehow I've seen it to be the `package-template`

**Comment by jdavies-st** [comment]
Would adding a `pyproject.toml` to this repo that specifically lists `setuptools` in it solve this issue?

**Comment by jdavies-st** [comment]
> https://app.circleci.com/jobs/github/sunpy/sunpy/38485/parallel-runs/0/steps/0-108

In the above traceback, `pkg_resources` is needed by `sphinx`, not `pytest-doctestplus`, so I suspect this is a CI configuration issue and not specific to this pytest plugin?

**Comment by astrofrog** [comment]
Looks like we maybe need to explicitly add setuptools as an install_requires dependency in setup.py? (Since it is a runtime dependency I’m utils.py)

**Comment by Anthchirp** [comment]
Just hit the [exact same issue](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=236305&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=10fc5aa2-324e-5982-4c88-6b31fcab16b3&l=6162) on conda-forge. Yes, setuptools should be listed as a runtime dependency. I'll put in a pull request
